import ISO6391 from 'iso-639-1';
import countries from 'svg-country-flags/countries.json';

const languages = ISO6391.getLanguages(ISO6391.getAllCodes());

export default {
  email: {
    type: 'text',
    defaultValue: '',
  },
  name: {
    type: 'text',
    defaultValue: '',
  },
  avatar: {
    type: 'text',
    defaultValue: '',
  },
  title: {
    type: 'text',
    defaultValue: '',
  },
  description: {
    type: 'longtext',
    defaultValue: '',
    style: {
      width: '100%'
    }
  },
  country: {
    type: 'select',
    defaultValue: '',
    options: Object.entries(countries).map(([code, name]) => ({
      label: name,
      value: code,
    }))
  },
  spokenLanguages: {
    type: 'tags',
    defaultValue: [],
    options: languages.map(lang => ({
      value: lang.code,
      label: lang.name,
    }))
  },
  tags: {
    type: 'tags',
    defaultValue: [],
    options: [
      '.net',
      '.netcore',
      '3d',
      'a11y',
      'accessibility',
      'adobe',
      'ai',
      'algorithms',
      'android',
      'angular',
      'angularjs',
      'apex',
      'api',
      'api-design',
      'apps script',
      'architecture',
      'arduino',
      'asp.net',
      'asp.net core',
      'automation',
      'aws',
      'azure',
      'backend',
      'best-practices',
      'blogging',
      'bootstrap',
      'build',
      'c',
      'c++',
      'c-sharp',
      'career',
      'cloud',
      'codeigniter',
      'command-line',
      'compassion',
      'computability',
      'css',
      'css-in-js',
      'd3js',
      'data',
      'data structures',
      'database',
      'ddd',
      'design',
      'design system',
      'devops',
      'distributed systems',
      'django',
      'docker',
      'e6',
      'ecommerce',
      'education',
      'electron.js',
      'elixir',
      'elm',
      'ethereum',
      'express',
      'figma',
      'firebase',
      'flutter',
      'fp',
      'frontend',
      'fullstack',
      'functional',
      'gamedev',
      'gatsby',
      'git',
      'go',
      'golang',
      'graphql',
      'growth hacking',
      'html',
      'hugo',
      'ibm cloud',
      'inclusion',
      'integration',
      'interviews',
      'intro',
      'ionic',
      'ios',
      'jamstack',
      'java',
      'javascript',
      'jest',
      'jquery',
      'kafka',
      'kotlin',
      'kubernetes',
      'laravel',
      'leadership',
      'linux',
      'lua',
      'magento',
      'management',
      'markup',
      'mean stack',
      'microservices',
      'mobile',
      'mobx',
      'modern php',
      'mongodb',
      'mssql',
      'mysql',
      'nestjs',
      'nextjs',
      'ngrx',
      'nodejs',
      'nosql',
      'objc',
      'opensource',
      'operations',
      'p2p',
      'performance',
      'phoenix fwk',
      'php',
      'platform',
      'podcast',
      'postgresql',
      'powershell',
      'principles',
      'product',
      'programming',
      'prototyping',
      'pug',
      'pwa',
      'python',
      'rails',
      'react native',
      'reactjs',
      'redis',
      'redux',
      'remote work',
      'rest',
      'ruby',
      'ruby on rails',
      'rust',
      'rx',
      'rxjs',
      'salesforce',
      'sass',
      'scalability',
      'scrum',
      'security',
      'selenium',
      'serverless',
      'sketch',
      'sketch plugins',
      'socket.io',
      'software-design',
      'solidus',
      'speaking',
      'spree',
      'spring',
      'sql',
      'sql server',
      'start-ups',
      'stenciljs',
      'stimulusjs',
      'svg',
      'swift',
      'swoole',
      'symfony',
      'sysadmin',
      'tailwind',
      'tdd',
      'tensorflow',
      'testing',
      'tooling',
      'tsql',
      'typescript',
      'ui',
      'umbraco',
      'unit testing',
      'unity',
      'uwp',
      'ux',
      'visual design',
      'vuejs',
      'watson',
      'web',
      'web automation',
      'web typography',
      'web apis',
      'web development',
      'webassembly',
      'webscraping',
      'wireframing',
      'wordpress',
      'xamarin',
      'xamarin forms',
      'xaml'
    ].map(tag => ({value: tag, label: tag})),
  },
};
