export const mockMentors = [
  {
    "_id": "616983adaac54156d3ab5de1",
    "available": true,
    "spokenLanguages": ["en", "fr"],
    "tags": ["javascript", "reactjs", "nodejs", "css", "html"],
    "name": "Alice B Johnson",
    "avatar": "/avatars/a1b2c3d4e5f6g7h8i9j0",
    "title": "Frontend Architect",
    "description": "Passionate frontend engineer with expertise in React and modern web development.",
    "country": "CA",
    "createdAt": "2020-05-10T09:15:30.000Z",
    "channels": []
  },
  {
    "_id": "616983adaac54156d3ab5de2",
    "available": false,
    "spokenLanguages": ["en", "de"],
    "tags": ["python", "django", "flask", "sql", "cloud"],
    "name": "Martin Schmidt",
    "avatar": "/avatars/abc123def456ghi789",
    "title": "Backend Specialist",
    "description": "Experienced backend engineer with a focus on Python and scalable web services.",
    "country": "DE",
    "createdAt": "2019-08-22T15:42:10.000Z",
    "channels": []
  },
  {
    "_id": "616983adaac54156d3ab5de4",
    "available": true,
    "spokenLanguages": ["en", "zh"],
    "tags": ["golang", "microservices", "cloud", "kubernetes"],
    "name": "Li Wei",
    "avatar": "/avatars/xyz987lmn654opq321",
    "title": "Cloud Engineer",
    "description": "Building scalable cloud applications with Go and Kubernetes.",
    "country": "CN",
    "createdAt": "2022-02-14T10:00:00.000Z",
    "channels": []
  },
  {
    "_id": "616983adaac54156d3ab5de5",
    "available": false,
    "spokenLanguages": ["en", "it"],
    "tags": ["java", "spring", "sql", "microservices"],
    "name": "Giovanni Rossi",
    "avatar": "/avatars/lmnop456rst789uvw123",
    "title": "Enterprise Java Developer",
    "description": "Building high-performance enterprise applications using Java and Spring.",
    "country": "IT",
    "createdAt": "2018-07-30T14:25:00.000Z",
    "channels": []
  },
  {
    "_id": "616983adaac54156d3ab5de6",
    "available": true,
    "spokenLanguages": ["en"],
    "tags": ["ruby", "rails", "postgresql", "devops"],
    "name": "Sophia Carter",
    "avatar": "/avatars/abcdef123456ghijk789",
    "title": "Ruby on Rails Expert",
    "description": "Helping startups build robust applications with Rails.",
    "country": "US",
    "createdAt": "2017-11-21T08:30:00.000Z",
    "channels": []
  },
  {
    "_id": "616983adaac54156d3ab5de7",
    "available": false,
    "spokenLanguages": ["en", "pt"],
    "tags": ["php", "laravel", "mysql", "api"],
    "name": "Carlos Mendes",
    "avatar": "/avatars/xyz123uvw456rst789",
    "title": "PHP & Laravel Developer",
    "description": "Specialized in building modern web applications using Laravel and PHP.",
    "country": "BR",
    "createdAt": "2021-01-10T17:45:00.000Z",
    "channels": []
  },
  {
    "_id": "616983adaac54156d3ab5de8",
    "available": true,
    "spokenLanguages": ["en", "ru"],
    "tags": ["c++", "game development", "unity", "opengl"],
    "name": "Ivan Petrov",
    "avatar": "/avatars/asdf1234ghjk5678lmno",
    "title": "Game Developer",
    "description": "Passionate about creating immersive gaming experiences with C++ and Unity.",
    "country": "RU",
    "createdAt": "2020-06-18T12:20:00.000Z",
    "channels": []
  },
  {
    "_id": "616983adaac54156d3ab5de9",
    "available": false,
    "spokenLanguages": ["en", "ja"],
    "tags": ["typescript", "vuejs", "nuxtjs", "frontend"],
    "name": "Haruto Tanaka",
    "avatar": "/avatars/jklm456nopq789rst123",
    "title": "Vue.js Frontend Engineer",
    "description": "Expert in building modern frontend applications with Vue.js and Nuxt.js.",
    "country": "JP",
    "createdAt": "2019-12-05T16:10:00.000Z",
    "channels": []
  },
  {
    "_id": "616983adaac54156d3ab5dea",
    "available": true,
    "spokenLanguages": ["en", "ar"],
    "tags": ["flutter", "dart", "mobile development"],
    "name": "Amira Khaled",
    "avatar": "/avatars/uvwxyz123456abcd789",
    "title": "Mobile App Developer",
    "description": "Building beautiful and efficient mobile apps with Flutter.",
    "country": "EG",
    "createdAt": "2023-03-01T09:00:00.000Z",
    "channels": []
  }
]